/*
=========================================================
* Material Kit 2 React - v2.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/material-kit-react
* Copyright 2023 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*/

// Sections components
import BaseLayout from "layouts/sections/components/BaseLayout";

// @mui material components
import Grid from "@mui/material/Grid";

// Material Kit 2 React components
import MKBox from "components/MKBox";
import MKTypography from "components/MKTypography";

// Material Kit 2 React examples
import AcupuntureImage from "assets/images/acupunture.png";

function Features() {
  return (
    <BaseLayout
      breadcrumb={[
        { label: "History", route: "/pages/landing-pages/history" },
        { label: "Moxibustion" },
      ]}
    >
      <MKBox component="section">
        <Grid container>
          <MKTypography variant="h3" mt={6} mb={3}>
            The origin of Moxibustion
          </MKTypography>

          <MKBox
            component="img"
            src="https://cdn.britannica.com/27/199927-050-85B901E3/moxibustion-cones-moxa-treatment-points-top-needles.jpg"
            alt="Traditional Chinese Medicine"
            borderRadius="lg"
            width="100%"
            mb={3}
            sx={{ maxHeight: "400px", objectFit: "cover" }}
          />

          <MKTypography variant="body2" color="text" sx={{ textAlign: "justify" }}>
            The origin of moxibustion is deeply intertwined with the discovery of fire, a pivotal
            moment in human history that not only revolutionized survival but also laid the
            groundwork for early medicine and pharmacology. Early humans, while navigating the
            challenges of their environment, discovered that fire could serve multiple purposes
            beyond providing warmth and protection. Initially, fire was used to cook food, making it
            easier to digest and enhancing its flavor. This discovery was transformative, as it
            allowed humans to consume a wider variety of foods and extract more nutrients, which
            contributed to their overall health and survival.
          </MKTypography>

          <MKBox
            component="img"
            src="https://media.istockphoto.com/id/1194512789/photo/neanderthal-or-homo-sapiens-family-cooking-animal-meat-over-bonfire-and-then-eating-it-tribe.jpg?s=612x612&w=0&k=20&c=-HUACskmDwnRH5HoVTr3IN4p09NREe9nOvfqdsTgoVk="
            alt="Traditional Chinese Medicine"
            borderRadius="lg"
            width="100%"
            mb={3}
            mt={3}
            sx={{ maxHeight: "700px", objectFit: "cover" }}
          />

          <MKTypography variant="body2" color="text" sx={{ textAlign: "justify" }} mb={3}>
            Over time, humans began to observe the therapeutic effects of heat. They noticed that
            applying heat to specific areas of the body could alleviate pain, improve circulation,
            and promote healing. This realization led to the development of rudimentary techniques
            such as the ironing method, where heated objects were applied to the body to provide
            relief. These practices eventually evolved into more sophisticated methods, including
            moxibustion.
          </MKTypography>

          <MKTypography variant="body2" color="text" sx={{ textAlign: "justify" }} mb={3}>
            Moxibustion, in particular, became a cornerstone of traditional Chinese medicine. This
            technique involves burning moxa, a dried plant material, near the skin to stimulate
            circulation and enhance the body's natural healing processes. The heat generated by the
            burning moxa was found to penetrate deeply into the body, targeting specific points to
            restore balance and harmony. This practice was not only used to treat physical ailments
            but also to prevent illnesses by strengthening the body's resistance to disease.
          </MKTypography>

          <MKTypography variant="body2" color="text" sx={{ textAlign: "justify" }}>
            The discovery of fire and its application in therapeutic practices like moxibustion
            marked the beginning of a systematic approach to healing. It demonstrated an early
            understanding of the connection between external stimuli and internal health, paving the
            way for the development of traditional medicine. These early innovations highlight the
            ingenuity of ancient humans and their ability to harness natural elements to improve
            their quality of life. Moxibustion remains a testament to this legacy, continuing to be
            practiced and revered in traditional Chinese medicine for its profound healing
            properties.
          </MKTypography>
        </Grid>
      </MKBox>
    </BaseLayout>
  );
}

export default Features;
