// Sections components
import BaseLayout from "layouts/sections/components/BaseLayout";

// @mui material components
import Grid from "@mui/material/Grid";
import Container from "@mui/material/Container";

// Material Kit 2 React components
import MKBox from "components/MKBox";
import MKTypography from "components/MKTypography";

function Features() {
  return (
    <BaseLayout
      breadcrumb={[
        { label: "History", route: "/pages/landing-pages/history" },
        { label: "Moxibustion" },
      ]}
    >
      <MKBox component="section">
        <Grid container>
          <MKTypography variant="h3" mt={6} mb={3}>
            The origin of Moxibustion
          </MKTypography>

          <MKBox
            component="img"
            src="https://cdn.britannica.com/27/199927-050-85B901E3/moxibustion-cones-moxa-treatment-points-top-needles.jpg"
            alt="Traditional Chinese Medicine"
            borderRadius="lg"
            width="100%"
            mb={3}
            sx={{ maxHeight: "400px", objectFit: "cover" }}
          />

          <MKTypography variant="body2" color="text" sx={{ textAlign: "justify" }}>
            The origin of moxibustion is deeply intertwined with the discovery of fire, a pivotal
            moment in human history that not only revolutionized survival but also laid the
            groundwork for early medicine and pharmacology. Early humans, while navigating the
            challenges of their environment, discovered that fire could serve multiple purposes
            beyond providing warmth and protection. Initially, fire was used to cook food, making it
            easier to digest and enhancing its flavor. This discovery was transformative, as it
            allowed humans to consume a wider variety of foods and extract more nutrients, which
            contributed to their overall health and survival.
          </MKTypography>

          <MKBox
            component="img"
            src="https://media.istockphoto.com/id/1194512789/photo/neanderthal-or-homo-sapiens-family-cooking-animal-meat-over-bonfire-and-then-eating-it-tribe.jpg?s=612x612&w=0&k=20&c=-HUACskmDwnRH5HoVTr3IN4p09NREe9nOvfqdsTgoVk="
            alt="Traditional Chinese Medicine"
            borderRadius="lg"
            width="100%"
            mb={3}
            mt={3}
            sx={{ maxHeight: "700px", objectFit: "cover" }}
          />

          <MKTypography variant="body2" color="text" sx={{ textAlign: "justify" }} mb={3}>
            Over time, humans began to observe the therapeutic effects of heat. They noticed that
            applying heat to specific areas of the body could alleviate pain, improve circulation,
            and promote healing. This realization led to the development of rudimentary techniques
            such as the ironing method, where heated objects were applied to the body to provide
            relief. These practices eventually evolved into more sophisticated methods, including
            moxibustion.
          </MKTypography>

          <MKTypography variant="body2" color="text" sx={{ textAlign: "justify" }} mb={3}>
            Moxibustion, in particular, became a cornerstone of traditional Chinese medicine. This
            technique involves burning moxa, a dried plant material, near the skin to stimulate
            circulation and enhance the body's natural healing processes. The heat generated by the
            burning moxa was found to penetrate deeply into the body, targeting specific points to
            restore balance and harmony. This practice was not only used to treat physical ailments
            but also to prevent illnesses by strengthening the body's resistance to disease.
          </MKTypography>

          <MKTypography variant="body2" color="text" sx={{ textAlign: "justify" }} mb={6}>
            The discovery of fire and its application in therapeutic practices like moxibustion
            marked the beginning of a systematic approach to healing. It demonstrated an early
            understanding of the connection between external stimuli and internal health, paving the
            way for the development of traditional medicine. These early innovations highlight the
            ingenuity of ancient humans and their ability to harness natural elements to improve
            their quality of life. Moxibustion remains a testament to this legacy, continuing to be
            practiced and revered in traditional Chinese medicine for its profound healing
            properties.
          </MKTypography>
        </Grid>
      </MKBox>

      <MKBox
        component="section"
        variant="gradient"
        bgColor="dark"
        position="relative"
        py={6}
        px={{ xs: 2, lg: 0 }}
        mx={-2}
      >
        <Container>
          <Grid container>
            <MKTypography variant="h3" color="white">
              From Fire to Smart Devices: The Evolution of Moxibustion
            </MKTypography>
            <MKTypography variant="body2" color="white" opacity={0.8} mt={3} textAlign="justify">
              Just as the discovery of fire was a turning point in human history—helping early
              humans stay warm, cook food, and eventually discover the healing power of heat—the
              development of modern technology has brought about a new kind of transformation in
              medicine. In ancient times, people noticed that applying heat to the body could
              relieve pain and help with healing. This led to early techniques like moxibustion,
              where burning dried herbs (usually mugwort) near the skin helped improve circulation
              and restore balance in the body. That discovery came from closely observing nature and
              experimenting with simple tools—just like how people today use computers and machines
              to solve complex problems.
            </MKTypography>

            <MKTypography variant="body2" color="white" opacity={0.8} mt={3} textAlign="justify">
              Now, in the same way that fire changed how people lived and healed, the rise of
              electricity, computers, and artificial intelligence (AI) is changing how we understand
              and improve traditional practices like moxibustion. Scientists and doctors can now use
              tools like thermal cameras to study how heat affects the body during moxibustion. They
              can collect data and use AI programs to find patterns in how patients respond to
              different treatments. This helps create better, more personalized treatment plans.
              There are even smart moxibustion devices and apps that guide people on where and how
              to apply heat based on traditional Chinese medicine principles and modern medical
              data.
            </MKTypography>

            <MKBox
              component="img"
              src="https://www.jrheum.org/content/jrheum/48/6/924/F2.large.jpg"
              alt="Traditional Chinese Medicine"
              borderRadius="lg"
              width="100%"
              mb={3}
              mt={3}
              sx={{ maxHeight: "400px", objectFit: "cover" }}
            />

            <MKTypography variant="body2" color="white" opacity={0.8} mt={3} textAlign="justify">
              Additionally, modern advancements have led to the development of innovative
              moxibustion techniques such as microwave moxibustion, laser moxibustion, and
              electrothermal moxibustion. These methods simulate the traditional effects of
              moxibustion using physical or chemical processes. For example, microwave moxibustion
              uses microwaves to generate heat, while laser moxibustion uses concentrated light
              energy to stimulate acupuncture points, and electrothermal moxibustion uses electrical
              currents to achieve similar therapeutic effects. These modern techniques provide new
              ways to apply the healing power of heat with greater precision and less discomfort,
              offering patients a more comfortable and effective alternative to traditional
              moxibustion.
            </MKTypography>

            <MKTypography variant="body2" color="white" opacity={0.8} mt={3} textAlign="justify">
              So, while fire was the first technology that helped people heal using heat, today's
              technology—powered by electricity and guided by computer science—is continuing that
              journey. Both moments in history show how human creativity and curiosity lead to new
              ways of caring for health. One used flames; the other uses information. But in the
              end, both help people live healthier, more balanced lives.
            </MKTypography>
          </Grid>
        </Container>
      </MKBox>
    </BaseLayout>
  );
}

export default Features;
